jmena = []
text1 = input(f"První prvek")
text2 = input(f"Druhý prvek")
text3 = input(f"Třetí prvek")
jmena.append(text1)
jmena.append(text2)
jmena.append(text3)
print(f"Všechny jmena {jmena}")
print(f"První jmeno {jmena[0]}")
print(f"Druhý jmeno {jmena[1]}")
print(f"Tretí jmeno {jmena[2]}")